# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def base_pods
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.3'
  pod 'Kingfisher', '~> 4.0'
  pod 'R.swift'
  pod 'Toast-Swift', '~> 3.0.1'
  pod 'CLImagePickerTool', :git => 'https://github.com/Darren-chenchen/CLImagePickerTool.git'
  pod 'ReachabilitySwift'
end

target 'MGBaseSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MGBaseSwift
  base_pods

end
